var ActionTypes = {
    ADD_SOURCE: 'ADD_SOURCE',
    DELETE_SOURCE: 'DELETE_SOURCE',
    CHECK_SOURCE: 'CHECK_SOURCE',
    STAPLE_SOURCE: 'STAPLE_SOURCE',
    COLOR_SOURCE: 'COLOR_SOURCE',
    CHANGE_ALPHA: 'CHANGE_ALPHA',
    CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',
    CHANGE_MODAL: 'CHANGE_MODAL'
};

module.exports = ActionTypes;
