const ActionTypes = {
    ADD_SOURCE: 'ADD_SOURCE',
    DELETE_SOURCE: 'DELETE_SOURCE',
    CHECK_SOURCE: 'CHECK_SOURCE',
    STAPLE_SOURCE: 'STAPLE_SOURCE',
    COLOR_SOURCE: 'COLOR_SOURCE',
    CHANGE_RGB: 'CHANGE_RGB',
    CHANGE_ALPHARANGE: 'CHANGE_ALPHARANGE',
    CHANGE_STROKECOLOR: 'CHANGE_STROKECOLOR',
    CHANGE_TEXTSCALE: 'CHANGE_TEXTSCALE',
    CHANGE_OUTLINECOLOR: 'CHANGE_OUTLINECOLOR',
    CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',
    CHANGE_MODAL: 'CHANGE_MODAL'
};

export default ActionTypes;
